# Generated by Django 4.0.3 on 2022-03-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_users_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create_users',
            new_name='CreateUsers',
        ),
    ]
